Finished release 1.0.0
- Added ability to create cartridges with `tic80-develop`.
- Added configuration support.
- Made script style consistent
- Other minor changes

diff --git a/tic80-develop b/tic80-develop
--- a/tic80-develop
+++ b/tic80-develop
@@ -1,77 +1,153 @@
 #!/usr/bin/env bash
 
+TIC80_START_PATH=${TIC80_START_PATH:-$HOME/.local/share/com.nesbox.tic/TIC-80}
+
 function print_usage() {
-    echo "Usage: tic80-develop [options] cart"
-    echo
-    echo "This script loads a TIC-80 cartridge for development."
-    echo "By default, this script will load a cartridge and set the"
-    echo "filesystem to the base path of the cartridge."
-    echo "Use tic80 for the normal binary."
-    echo
-    echo "Options:"
-    echo -e "\t-h, --help\tshow this help message and exit"
-    echo -e "\t--skip\t\tskip startup animation"
-    echo -e "\t--volume=<int>\tglobal volume value [0-15]"
-    echo -e "\t--fullscreen\tenable fullscreen mode"
-    echo -e "\t--vsync\t\tenable VSYNC"
-    echo -e "\t--soft\t\tuse software rendering"
-    echo -e "\t--scale=<int>\tmain window scale"
+    printf "Usage: tic80-develop [options] cart\n\n"
+
+    printf "This script loads a TIC-80 cartridge for development. By default, this script will load a cartridge and set the filesystem to the base path of the cartridge.\n"
+    printf "Use tic80 for the normal binary.\n\n"
+
+    printf "Options:\n"
+    printf "\t-h, --help\tshow this help message and quit\n"
+    printf "\t--skip\t\tskip startup animation\n"
+    printf "\t--volume=<int>\tglobal volume value [0-15]\n"
+    printf "\t--fullscreen\tenable fullscreen mode\n"
+    printf "\t--vsync\t\tenable VSYNC\n"
+    printf "\t--soft\t\tuse software rendering\n"
+    printf "\t--scale=<int>\tmain window scale\n"
+    printf "\t--universal\tall paths accessible\n"
+    printf "\t--config=<str>\tpath to configuration\n"
 }
 
-# Parse options
-declare -a OPTIONS=()
+function quit() {
+    if [[ -h $cartridge_path/.local ]]; then
+        rm $cartridge_path/.local
+    fi
+	unset options option value config universal cartridge cartridge_name cartridge_path format
+	exit $1
+}
+
+# Check binary
+if ! which tic80 &> /dev/null; then
+	printf "error: tic80 not installed\n" > /dev/stderr
+	quit 1
+fi
+
+# Prepare arguments
+config=$TIC80_START_PATH/.local
+universal=false
+declare -a options=()
 while [[ $1 =~ ^--? ]]; do
-    OPTION=$1
-    if [[ $OPTION =~ -h|--help ]]; then
-        print_usage
-        exit 0
-    elif [[ $1 =~ ^(--skip|--fullscreen|--vsync|--soft)$ ]]; then
-        OPTIONS=( ${OPTIONS[@]/$OPTION/} )
-        OPTIONS+=( $OPTION )
-    elif [[ $OPTION =~ ^--volume ]]; then
-        OPTIONS=( ${OPTIONS[@]/^--volume/} )
-        if [[ $OPTION =~ ^--volume$ ]]; then
-            shift; OPTIONS+=( --volume=$1 )
-        elif [[ $OPTION =~ ^--volume=[0-9]+$ ]]; then
-            OPTIONS+=( $OPTION )
+    option=$1
+    if [[ $option =~ -h|--help ]]; then
+		print_usage
+        quit 0
+    elif [[ $option =~ ^(--skip|--fullscreen|--vsync|--soft)$ ]]; then
+        options=( ${options[@]/$option/} )
+        options+=( $option )
+    elif [[ $option == --universal ]]; then
+        universal=true
+    elif [[ $option =~ ^--volume ]]; then
+        options=( ${options[@]/^--volume/} )
+        if [[ $option =~ ^--volume$ ]]; then
+            shift; value=$1
+            if [[ ! $value =~ ^[0-9]+$ ]]; then
+            	printf "error: option \`--volume\` expectes an integer value\n" > /dev/stderr
+            	quit 1
+            fi
+            options+=( --volume=$value )
+        elif [[ $option =~ ^--volume=[0-9]+$ ]]; then
+            options+=( $option )
         else
-            echo "error: option \`--volume\` expects an integer value"
-            exit 1
+            printf "error: option \`--volume\` expects an integer value\n" > /dev/stderr
+            quit 1
         fi
-    elif [[ $OPTION =~ ^--scale ]]; then
-        OPTIONS=( ${OPTIONS[@]/^--scale/} )
-        if [[ $OPTION == --scale ]]; then
-            shift; OPTIONS+=( --scale=$1 )
-        elif [[ $OPTION =~ ^--scale=[0-9]+$ ]]; then
-            OPTIONS+=( $OPTION )
+    elif [[ $option =~ ^--scale ]]; then
+        options=( ${options[@]/^--scale/} )
+        if [[ $option == --scale ]]; then
+            shift; value=$1
+            if [[ ! $value =~ ^[0-9]+$ ]]; then
+            	printf "error: option \`--scale\` expectes an integer value\n" > /dev/stderr
+            	quit 1
+            fi
+            options+=( --scale=$value )
+        elif [[ $option =~ ^--scale=[0-9]+$ ]]; then
+            options+=( $option )
         else
-            echo "error: option \`--scale\` expects an integer value"
-            exit 1
+            printf "error: option \`--scale\` expects an integer value\n" > /dev/stderr
+            quit 1
+        fi
+    elif [[ $option =~ ^--config ]]; then
+        if [[ $option == --config ]]; then
+            shift; config=$1
+        elif [[ $option =~ ^--config=.+$ ]]; then
+            config=$(cut -d "=" -f 2- <<< $option)
+        else
+            printf "error: option \`--config\` expects a string value\n" > /dev/stderr
+            quit 1
         fi
     else
-        echo "error: unknown option \`$OPTION\`"
-        print_usage
-        exit 1
+        printf "error: unknown option \`$option\`\n" > /dev/stderr
+        print_usage > /dev/stderr
+        quit 1
     fi
     shift
 done
 
-# Check binary
-if [[ -z $(which tic80) ]]; then
-    echo "error: tic80 not installed"
-    exit 1
+if $universal && [[ $config != $TIC80_START_PATH/.local ]]; then
+    printf "error: options \`--config\` and \`--universal\` are mutually exclusive\n" > /dev/stderr
+    quit 1
 fi
 
-# Check cartridge
-CARTRIDGE=$1
-if [[ -z $CARTRIDGE ]]; then
-    echo "error: no cartridge specified"
-    exit 1
-elif [[ ! -e $CARTRIDGE ]]; then
-	echo "error: cartridge \`$CARTRIDGE\` does not exist"
-	exit 1
+# Prepare cartridge
+cartridge=$(readlink -f $1 2> /dev/null)
+if [[ -z $cartridge ]]; then
+	printf "error: no cartridge specified\n" > /dev/stderr
+	quit 1
 fi
-CARTRIDGE_PATH=$(dirname $CARTRIDGE)
-CARTRIDGE_FILE=$(basename $CARTRIDGE)
+cartridge_path=$(dirname $cartridge)
+cartridge_name=$(basename $cartridge)
 
-tic80 ${OPTIONS[@]} --fs="$CARTRIDGE_PATH" --cmd="load $CARTRIDGE_FILE"
+# Link configuration
+if ! $universal; then
+    if [[ ! -d $config ]]; then
+        printf "warning: option \`--config\` is not a valid config directory; using \`$TIC80_START_PATH/.local\` instead\n" > /dev/stderr
+        config="$TIC80_START_PATH/.local"
+    fi
+    ln -s $config $cartridge_path/.local
+fi
+
+# Create or load catridge
+if [[ -e $cartridge ]]; then
+    if ! $universal; then
+        tic80 "${options[@]}" --fs="$cartridge_path" --cmd="load $cartridge_name"
+    else
+        tic80 "${options[@]}" --fs="/" --cmd="cd $cartridge_path & load $cartridge_name"
+    fi
+    quit $?
+else
+    case $cartridge in
+        *.tic|*.lua)	format="lua";;
+        *.rb)			format="ruby";;
+        *.js)			format="js";;
+        *.moon)			format="moon";;
+        *.fnl)			format="fennel";;
+        *.scm)			format="scheme";;
+        *.nut)			format="squirrel";;
+        *.wren)			format="wren";;
+        *.janet)		format="janet";;
+        *.py)			format="python";;
+        *.wasm)			format="wasm";;
+        *)
+            printf "error: invalid cartridge format \`.${cartridge##*.}\`\n" > /dev/stderr
+            quit 1
+            ;;
+    esac
+    if ! $universal; then
+        tic80 "${options[@]}" --fs="$cartridge_path" --cmd="new $format & save $cartridge_name"
+    else
+        tic80 "${options[@]}" --fs="/" --cmd="cd $cartridge_path & new $format & save $cartridge_name"
+    fi 
+    quit $?
+fi
diff --git a/tic80-export b/tic80-export
--- a/tic80-export
+++ b/tic80-export
@@ -1,152 +1,160 @@
 #!/usr/bin/env bash
 
 function print_usage() {
-    echo "Usage: tic80-export [options] cart format filename"
-    echo
-    echo "This script exports TIC-80 cartridge data in the specified format type."
-    echo "Use tic80 for the normal binary."
-    echo
-    echo "Options:"
-    echo -e "\t-h,--h\t\tshow this help message and exit"
-    echo -e "\t--id=<int>\texport selected sound effect [0-63] or music track [0-7] (default: 0)"
-    echo "PRO Edition Options:"
-    echo -e "\t--alone\t\texport without editors"
-    echo -e "\t--bank=<int>\texport from selected bank [0-7] (default: 0)"
-    echo -e "\t--vbank=<int>\texport from selected VRAM bank [0-1] (default: 0)"
-    echo "Formats:"
-    echo -e "\twin\t\tWindows application"
-    echo -e "\twinxp\t\tWindows XP application"
-    echo -e "\tlinux\t\tLinux application"
-    echo -e "\trpi\t\tRaspberry PI application"
-    echo -e "\tmac\t\tMacintosh application"
-    echo -e "\thtml\t\tWeb application"
-    echo -e "\ttiles\t\ttiles as .png image"
-    echo -e "\tsprites\t\tsprites as .png image"
-    echo -e "\tmap\t\tmap as .map file"
-    echo -e "\tmapimg\t\tmap as .png image"
-    echo -e "\tsfx\t\tsound effects as .wav sound"
-    echo -e "\tmusic\t\tmusic as .wav sound"
-    echo -e "\tscreen\t\tscreen as .png image"
+    printf "Usage: tic80-export [options] cart data file\n\n"
+
+    printf "This script exports TIC-80 cartridge data in the specified format type.\n"
+    printf "Use tic80 for the normal binary.\n\n"
+
+    printf "Options:\n"
+    printf "\t-h,--help\tshow this help message and exit\n"
+    printf "\t--id=<int>\texport selected sound effect [0-63] or music track [0-7] (default: 0)\n\n"
+
+    printf "PRO Edition Options:\n"
+    printf "\t--alone\t\texport without editors\n"
+    printf "\t--bank=<int>\texport from selected bank [0-7] (default: 0)\n"
+    printf "\t--vbank=<int>\texport from selected VRAM bank [0-1] (default: 0)\n\n"
+
+    printf "Data Formats:\n"
+    printf "\twin\t\tWindows application\n"
+    printf "\twinxp\t\tWindows XP application\n"
+    printf "\tlinux\t\tLinux application\n"
+    printf "\trpi\t\tRaspberry PI application\n"
+    printf "\tmac\t\tMacintosh application\n"
+    printf "\thtml\t\tWeb application\n"
+    printf "\ttiles\t\ttiles as .png image\n"
+    printf "\tsprites\t\tsprites as .png image\n"
+    printf "\tmap\t\tmap as .map file\n"
+    printf "\tmapimg\t\tmap as .png image\n"
+    printf "\tsfx\t\tsound effects as .wav sound\n"
+    printf "\tmusic\t\tmusic as .wav sound\n"
+    printf "\tscreen\t\tscreen as .png image\n"
+}
+
+function quit() {
+    unset options option value pro_required cartridge cartridge_path cartridge_name data extension file tempfile
+    exit $1
 }
 
 # Parse options
-NEED_PRO=1
-declare -a OPTIONS=()
+pro_required=false
+declare -a options=()
 while [[ $1 =~ ^--? ]]; do
-    if [[ $1 =~ ^(-h|--help) ]]; then
+    option=$1
+    if [[ $option =~ ^(-h|--help) ]]; then
         print_usage
-        exit 0
-    elif [[ $1 =~ ^--alone ]]; then
-        NEED_PRO=0
-        OPTIONS=( ${OPTIONS[@]/^alone=1$/} )
-        OPTIONS+="alone=1"
-    elif [[ $1 =~ ^--bank ]]; then
-        NEED_PRO=0
-        if [[ $1 =~ ^--bank$ ]]; then
-            shift
-            OPTIONS=( ${OPTIONS[@]/^bank=[0-9]+$/} )
-            OPTIONS+="bank=$1"
-        elif [[ $1 =~ ^--bank=[0-9]+$ ]]; then
-            OPTIONS=( ${OPTIONS[@]/^bank=[0-9]+$/} )
-            OPTIONS+="bank=${1#--bank=}"
+        quit 0
+    elif [[ $option =~ ^--alone ]]; then
+        pro_required=true
+        options=( ${options[@]/^alone=1$/} )
+        options+="alone=1"
+    elif [[ $option =~ ^--bank ]]; then
+        pro_required=true
+        if [[ $option =~ ^--bank$ ]]; then
+            shift; value=$1
+            if [[ ! $value =~ ^[0-9]+$ ]]; then
+                printf "error: option \`--bank\` expects an integer value" > /dev/stderr
+                quit 1
+            fi
+            options=( ${options[@]/^bank=[0-9]+$/} )
+            options+="bank=$1"
+        elif [[ $option =~ ^--bank=[0-9]+$ ]]; then
+            options=( ${options[@]/^bank=[0-9]+$/} )
+            options+="bank=${1#--bank=}"
         else
-            echo "error: option \`--bank\` expects an integer value"
-            exit 1
+            printf "error: option \`--bank\` expects an integer value\n" > /dev/stderr
+            quit 1
         fi
-    elif [[ $1 =~ ^--vbank ]]; then
-        NEED_PRO=0
-        if [[ $1 =~ ^--vbank$ ]]; then
-            shift
-            OPTIONS=( ${OPTIONS[@]/^vbank=[0-9]+$/} )
-            OPTIONS+="vbank=$1"
+    elif [[ $option =~ ^--vbank ]]; then
+        pro_required=true
+        if [[ $option =~ ^--vbank$ ]]; then
+            shift; value=$1
+            if [[ ! $value =~ ^[0-9]+$ ]]; then
+                printf "error: option \`--vbank\` expects an integer value" > /dev/stderr
+                quit 1
+            fi 
+            options=( ${options[@]/^vbank=[0-9]+$/} )
+            options+="vbank=$1"
         elif [[ $1 =~ ^--vbank=[0-9]+$ ]]; then
-            OPTIONS=( ${OPTIONS[@]/^vbank=[0-9]+$/} )
-            OPTIONS+="vbank=${1#--vbank=}"
+            options=( ${options[@]/^vbank=[0-9]+$/} )
+            options+="vbank=${1#--vbank=}"
         else
-            echo "error: option \`--vbank\` expects an integer value"
-            exit 1
+            printf "error: option \`--vbank\` expects an integer value\n" > /dev/stderr
+            quit 1
         fi
-    elif [[ $1 =~ ^--id ]]; then
-        if [[ $1 =~ ^--id$ ]]; then
-            shift
-            OPTIONS=( ${OPTIONS[@]/^id=[0-9]+$/} )
-            OPTIONS+="id=$1"
-        elif [[ $1 =~ ^--id=[0-9]+$ ]]; then
-            OPTIONS=( ${OPTIONS[@]/^id=[0-9]+$/} )
-            OPTIONS+="id=${1#--id=}"
+    elif [[ $option =~ ^--id ]]; then
+        if [[ $option =~ ^--id$ ]]; then
+            shift; value=$1
+            if [[ ! $value =~ ^[0-9]+$ ]]; then
+                printf "error: option \`--id\` expects an integer value" > /dev/stderr
+                quit 1
+            fi
+            options=( ${options[@]/^id=[0-9]+$/} )
+            options+="id=$1"
+        elif [[ $option =~ ^--id=[0-9]+$ ]]; then
+            options=( ${options[@]/^id=[0-9]+$/} )
+            options+="id=$(cut -d '=' -f 2- <<< $option)"
         else
-            echo "error: option \`--id\` expects an integer value"
-            exit 1
+            printf "error: option \`--id\` expects an integer value\n" > /dev/stderr
+            quit 1
         fi
     else
-        echo
+        print_usage > /dev/stderr
+        quit 1
     fi
     shift
 done
 
 # Check binary
-if [[ -z $(which tic80) ]]; then
-    echo "error: tic80 not installed"
-    exit 1
-elif [[ NEED_PRO && ! $(tic80 --version) =~ Pro ]]; then
-    echo "error: need tic80 PRO edition"
-    exit 1
+if ! which tic80 &> /dev/null; then
+    printf "error: tic80 not installed\n" > /dev/stderr
+    quit 1
+elif $pro_required && [[ ! $(tic80 --version) =~ Pro ]]; then
+    printf "error: need tic80 PRO edition\n" > /dev/stderr
+    quit 1
 fi
 
 # Check cartridge
-CARTRIDGE=$1
-if [[ -z $CARTRIDGE ]]; then
-    echo "error: no cartridge specified"
-    print_usage
-    exit 1
-elif [[ ! -e $1 ]]; then
-	echo "error: cartridge \`$CARTRIDGE\` does not exist"
-	exit 1
-elif [[ ! -f $CARTRIDGE || $(xdg-mime query filetype $CARTRIDGE) != application/x-tic80-cartridge ]]; then
-    echo "error: \`$CARTRIDGE\` is not a cartridge file"
-    exit 1
+cartridge=$1
+if [[ -z $cartridge ]]; then
+    printf "error: no cartridge specified\n" > /dev/stderr
+    print_usage > /dev/stderr
+    quit 1
+elif [[ ! -e $cartridge ]]; then
+	printf "error: cartridge \`$cartridge\` does not exist\n" > /dev/stderr
+	quit 1
 fi
-CARTRIDGE_FILE=$(basename $CARTRIDGE)
+cartridge_path=$(dirname $cartridge)
+cartridge_name=$(basename $cartridge)
+shift
 
 # Check format
-shift
-FORMAT=$1
-case $FORMAT in
-    linux|mac|rpi)
-        FILE_EXTENSION=""
-        ;;
-    win|winxp)
-        FILE_EXTENSION=".exe"
-        ;;
-    html)
-        FILE_EXTENSION=".zip"
-        ;;
-    tiles|sprites|mapimg|screen)
-        FILE_EXTENSION=".png"
-        ;;
-    map)
-        FILE_EXTENSION=".map"
-        ;;
-    sfx|music)
-        FILE_EXTENSION=".wav"
-        ;;
+data=$1
+case $data in
+    linux|mac|rpi)                  extension="";;
+    win|winxp)                      extension=".exe";;
+    html)                           extension=".zip";;
+    tiles|sprites|mapimg|screen)    extension=".png";;
+    map)                            extension=".map";;
+    sfx|music)                      extension=".wav";;
     *)
-        echo "error: invalid format \`$FORMAT\`"
-        print_usage
-        exit 1
+        printf "error: invalid format \`$data\`\n" > /dev/stderr
+        print_usage > /dev/stderr
+        quit 1
         ;;
 esac
+shift
 
 # Check file
-shift
-FILE=$1
-if [[ -z $FILE ]]; then
-    echo "error: no file specified"
-    print_usage
-    exit 1
+file=$1
+if [[ -z $file ]]; then
+    printf "error: no file specified\n" > /dev/stderr
+    print_usage > /dev/stderr
+    quit 1
 fi
-FILE_PATH=$(dirname $FILE)
-FILE_NAME=$(basename ${FILE%.*})
 
-tic80 --fs="$(dirname $CARTRIDGE)" --cmd="load $CARTRIDGE_FILE & export $FORMAT $FILE_NAME ${OPTIONS[@]}" > /dev/null
-mv $FILE_NAME$FILE_EXTENSION $FILE_PATH
+tempfile=".${cartridge_name%.*}-$data-$(cat /dev/urandom | tr -cd 0-9a-f | head -c 16)$extension"
+tic80 --cli --fs="$cartridge_path" --cmd="load $cartridge_name & export $data $tempfile ${options[@]} & exit"
+mv $tempfile $file
+printf "\e[1K\r$file exported :)\n"
+quit 0
diff --git a/tic80-play b/tic80-play
--- a/tic80-play
+++ b/tic80-play
@@ -1,78 +1,113 @@
 #!/usr/bin/env bash
 
+TIC80_START_PATH=${TIC80_START_PATH:-$HOME/.local/share/com.nesbox.tic/TIC-80}
+
 function print_usage() {
-    echo "Usage: tic80-play [options] cart"
-    echo
-    echo "This script immediately loads and plays a TIC-80 cartridge."
-    echo "Use tic80 for the normal binary."
-    echo
-    echo "Options:"
-    echo -e "\t-h, --help\tshow this help message and exit"
-    echo -e "\t--noskip\tdon't skip startup animation"
-    echo -e "\t--volume=<int>\tglobal volume value [0-15]"
-    echo -e "\t--fullscreen\tenable fullscreen mode"
-    echo -e "\t--vsync\t\tenable VSYNC"
-    echo -e "\t--soft\t\tuse software rendering"
-    echo -e "\t--scale=<int>\tmain window scale"
+    printf "Usage: tic80-play [options] cart\n\n"
+
+    printf "This script immediately loads and plays a TIC-80 cartridge.\n"
+    printf "Use tic80 for the normal binary.\n\n"
+
+    printf "Options:\n"
+    printf "\t-h, --help\tshow this help message and exit\n"
+    printf "\t--noskip\tdon't skip startup animation\n"
+    printf "\t--volume=<int>\tglobal volume value [0-15]\n"
+    printf "\t--fullscreen\tenable fullscreen mode\n"
+    printf "\t--vsync\t\tenable VSYNC\n"
+    printf "\t--soft\t\tuse software rendering\n"
+    printf "\t--scale=<int>\tmain window scale\n"
+    printf "\t--config=<str>\tpath to configuration\n"
+}
+
+function quit() {
+    unset options option value cartridge cartridge_name cartridge_path
+    exit $1
 }
 
 # Parse options
-declare -a OPTIONS=(--skip)
+config=$TIC80_START_PATH/.local
+declare -a options=( --skip )
 while [[ $1 =~ ^--? ]]; do
-    OPTION=$1
-    if [[ $OPTION =~ ^(-h|--help)$ ]]; then
-        print_usage
-        exit 0
-    elif [[ $1 =~ ^--noskip$ ]]; then
-        OPTIONS=( ${OPTIONS[@]/^--skip$/} )
-    elif [[ $1 =~ ^(--fullscreen|--vsync|--soft)$ ]]; then
-        OPTIONS=( ${OPTIONS[@]/$OPTION/} )
-        OPTIONS+=( $OPTION )
-    elif [[ $OPTION =~ ^--volume ]]; then
-        OPTIONS=( ${OPTIONS[@]/^--volume/} )
-        if [[ $OPTION =~ ^--volume$ ]]; then
-            shift; OPTIONS+=( --volume=$1 )
-        elif [[ $OPTION =~ ^--volume=[0-9]+$ ]]; then
-            OPTIONS+=( $OPTION )
+    option=$1
+    if [[ $option =~ ^(-h|--help)$ ]]; then
+        print_usage > /dev/stderr
+        quit 0
+    elif [[ $option =~ ^--noskip$ ]]; then
+        options=( ${options[@]/^--skip$/} )
+    elif [[ $option =~ ^(--fullscreen|--vsync|--soft)$ ]]; then
+        options=( ${options[@]/$option/} )
+        options+=( $option )
+    elif [[ $option =~ ^--volume ]]; then
+        options=( ${options[@]/^--volume/} )
+        if [[ $option =~ ^--volume$ ]]; then
+            shift; value=$1
+            if [[ ! $value =~ ^[0-9]+$ ]]; then
+                printf "error: option \`--volume\` expects an integer value" > /dev/stderr
+                quit 1
+            fi
+            options+=( --volume=$value )
+        elif [[ $option =~ ^--volume=[0-9]+$ ]]; then
+            options+=( $option )
         else
-            echo "error: option \`--volume\` expects an integer value"
-            exit 1
+            printf "error: option \`--volume\` expects an integer value" > /dev/stderr
+            quit 1
         fi
-    elif [[ $OPTION =~ ^--scale ]]; then
-        OPTIONS=( ${OPTIONS[@]/^--scale/} )
-        if [[ $OPTION == --scale ]]; then
-            shift; OPTIONS+=( --scale=$1 )
-        elif [[ $OPTION =~ ^--scale=[0-9]+$ ]]; then
-            OPTIONS+=( $OPTION )
+    elif [[ $option =~ ^--scale ]]; then
+        options=( ${options[@]/^--scale/} )
+        if [[ $option == --scale ]]; then
+            shift; value=$1
+            if [[ ! $value =~ ^[0-9]+$ ]]; then
+                printf "error: option \`--volume\` expects an integer value" > /dev/stderr
+                quit 1
+            fi
+            options+=( --scale=$value )
+        elif [[ $option =~ ^--scale=[0-9]+$ ]]; then
+            options+=( $option )
         else
-            echo "error: option \`--scale\` expects an integer value"
-            exit 1
+            printf "error: option \`--scale\` expects an integer value" > /dev/stderr
+            quit 1
+        fi
+    elif [[ $option =~ ^--config ]]; then
+        if [[ $option == --config ]]; then
+            shift; config=$1
+        elif [[ $option =~ ^--config=.+$ ]]; then
+            config=$(cut -d "=" -f 2- <<< $option)
+        else
+            printf "error: option \`--config\` expects a string value\n" > /dev/stderr
+            quit 1
         fi
     else
-        echo "error: unknown option \`$1\`"
-        print_usage
-        exit 1
+        printf "error: unknown option \`$option\`" > /dev/stderr
+        print_usage > /dev/stderr
+        quit 1
     fi
     shift
 done
 
 # Check binary
-if [[ -z $(which tic80) ]]; then
-    echo "error: tic80 not installed"
-    exit 1
+if ! which tic80 &> /dev/null; then
+    printf "error: tic80 not installed" > /dev/stderr
+    quit 1
 fi
 
 # Check cartridge
-CARTRIDGE=$1
-if [[ -z $CARTRIDGE ]]; then
-    echo "error: no cartridge specified"
-    exit 1
-elif [[ ! -e $CARTRIDGE ]]; then
-	echo "error: cartridge \`$CARTRIDGE\` does not exist"
-	exit 1
-elif [[ ! -f $CARTRIDGE || $(xdg-mime query filetype $CARTRIDGE) != application/x-tic80-cartridge ]]; then
-    echo "error: \`$1\` is not a cartridge file"
-    exit 1
+cartridge=$(readlink -f $1 2> /dev/null)
+if [[ -z $cartridge ]]; then
+    printf "error: no cartridge specified" > /dev/stderr
+    quit 1
+elif [[ ! -e $cartridge ]]; then
+	printf "error: cartridge \`$cartridge\` does not exist" > /dev/stderr
+	quit 1
 fi
+cartridge_path=$(dirname $cartridge)
+cartridge_name=$(basename $cartridge)
 
-tic80 $1 ${OPTIONS[@]}
+# Link configuration
+if [[ ! -d $config ]]; then
+    printf "warning: option \`--config\` is not a valid config directory; using \`$TIC80_START_PATH/.local\` instead\n" > /dev/stderr
+    config="$TIC80_START_PATH/.local"
+fi
+ln -s $config $cartridge_path/.local
+
+tic80 "${options[@]}" --cmd="load $cartridge_name & run & exit"
+quit $?
diff --git a/tic80-surf b/tic80-surf
--- a/tic80-surf
+++ b/tic80-surf
@@ -1,65 +1,81 @@
 #!/usr/bin/env bash
 
 function print_usage() {
-    echo "Usage: tic80-surf [options]"
-    echo
-    echo "This script starts the TIC-80 cartridge browser."
-    echo "Use tic80 for the normal binary."
-    echo
-    echo "Options:"
-    echo -e "\t-h, --help\tshow this help message and exit"
-    echo -e "\t--noskip\tdon't skip startup animation"
-    echo -e "\t--volume=<int>\tglobal volume value [0-15]"
-    echo -e "\t--fullscreen\tenable fullscreen mode"
-    echo -e "\t--vsync\t\tenable VSYNC"
-    echo -e "\t--soft\t\tuse software rendering"
-    echo -e "\t--scale=<int>\tmain window scale"
+    printf "Usage: tic80-surf [options]\n\n"
+
+    printf "This script starts the TIC-80 cartridge browser.\n"
+    printf "Use tic80 for the normal binary.\n\n"
+
+    printf "Options:\n"
+    printf "\t-h, --help\tshow this help message and quit\n"
+    printf "\t--noskip\tdon't skip startup animation\n"
+    printf "\t--volume=<int>\tglobal volume value [0-15]\n"
+    printf "\t--fullscreen\tenable fullscreen mode\n"
+    printf "\t--vsync\t\tenable VSYNC\n"
+    printf "\t--soft\t\tuse software rendering\n"
+    printf "\t--scale=<int>\tmain window scale\n"
 }
 
-# Parse options
-OPTIONS=(--skip)
+function quit() {
+    unset options option value
+    quit $1
+}
+
+# Check binary
+if ! which tic80 &> /dev/null; then
+    echo "error: tic80 not installed" > /dev/stderr
+    quit 1
+fi
+
+# Prepare options
+declare -a options=( --skip )
 while [[ $1 =~ ^--? ]]; do
-    OPTION=$1
-    if [[ $OPTION =~ ^(-h|--help)$ ]]; then
-        print_usage
-        exit 0
-    elif [[ $1 =~ ^--noskip$ ]]; then
-        OPTIONS=( ${OPTIONS[@]/^--skip$/} )
-    elif [[ $1 =~ ^(--fullscreen|--vsync|--soft)$ ]]; then
-        OPTIONS=( ${OPTIONS[@]/$1/} )
-        OPTIONS+=( $OPTION )
+    option=$1
+    if [[ $option =~ ^(-h|--help)$ ]]; then
+        print_usage > /dev/stderr
+        quit 0
+    elif [[ $option =~ ^--noskip$ ]]; then
+        options=( ${options[@]/^--skip$/} )
+    elif [[ $option =~ ^(--fullscreen|--vsync|--soft|--crt)$ ]]; then
+        options=( ${options[@]/$1/} )
+        options+=( $option )
     elif [[ $OPTION =~ ^--volume ]]; then
-        OPTIONS=( ${OPTIONS[@]/^--volume/} )
-        if [[ $OPTION =~ ^--volume$ ]]; then
-            shift; OPTIONS+=( --volume=$1 )
-        elif [[ $OPTION =~ ^--volume=[0-9]+$ ]]; then
-            OPTIONS+=( $OPTION )
+        options=( ${options[@]/^--volume/} )
+        if [[ $option =~ ^--volume$ ]]; then
+            shift; value=$1
+            if [[ ! $value =~ ^[0-9]+$ ]]; then
+                printf "error: option \`--volume\` expectes an integer value" > /dev/stderr
+                quit 1
+            fi
+            options+=( --volume=$value )
+        elif [[ $option =~ ^--volume=[0-9]+$ ]]; then
+            options+=( $option )
         else
-            echo "error: option \`--volume\` expects an integer value"
-            exit 1
+            echo "error: option \`--volume\` expects an integer value" > /dev/stderr
+            quit 1
         fi
-    elif [[ $OPTION =~ ^--scale ]]; then
-        OPTIONS=( ${OPTIONS[@]/^--scale/} )
-        if [[ $OPTION == --scale ]]; then
-            shift; OPTIONS+=( --scale=$1 )
-        elif [[ $OPTION =~ ^--scale=[0-9]+$ ]]; then
-            OPTIONS+=( $OPTION )
+    elif [[ $option =~ ^--scale ]]; then
+        options=( ${options[@]/^--scale/} )
+        if [[ $option == --scale ]]; then
+            shift; value=$1
+            if [[ ! $value =~ ^[0-9]+$ ]]; then
+                printf "error: option \`--scale\` expectes an integer value" > /dev/stderr
+                quit 1
+            fi
+            options+=( --scale=$value )
+        elif [[ $option =~ ^--scale=[0-9]+$ ]]; then
+            options+=( $option )
         else
-            echo "error: option \`--scale\` expects an integer value"
-            exit 1
+            echo "error: option \`--scale\` expects an integer value" > /dev/stderr
+            quit 1
         fi
     else
-        echo "error: unknown option \`$1\`"
-        print_usage
-        exit 1
+        echo "error: unknown option \`$option\`"
+        print_usage > /dev/stderr
+        quit 1
     fi
     shift
 done
 
-# Check binary
-if [[ -z $(which tic80) ]]; then
-    echo "error: tic80 not installed"
-    exit 1
-fi
-
-tic80 ${OPTIONS[@]} --cmd="surf"
+tic80 "${options[@]}" --cmd="surf"
+quit $?
